# This chart installs the custom grafana dashboards and datasources
namespace: ""
dashboards:
  label:
    grafana_dashboard: "1"
datasources:
  label:
    grafana_datasource: "1"

# You can add additional data sourcres below
additionalDataSources:
- name: Loki
  uid: P8E80F9AEF21F6940
  type: loki
  access: proxy
  url: http://loki-gateway.loki.svc.cluster.local
  jsonData:
    maxLines: 1000
# - name: prometheus
#   type: prometheus
#   url: http://obsrv-monitoring-prometheus.monitoring.svc.cluster.local
#   version: 1

# To add new dashboards, place the exported json in dashboards directory
# If any dashboards are added / modified / removed,
# bump up the chart version number in order to pick up changes