apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-console
  name: web-console
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-console
  template:
    metadata:
      labels:
        app: web-console
    spec:
      containers:
        - image: "{{ .Values.image.repository }}/{{ .Values.image.image_name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          name: web-console
          resources: 
            requests:
              cpu: "{{ .Values.cpu_requests }}"
              memory: "{{ .Values.memory_requests }}"
            limits:
              cpu: "{{ .Values.cpu_limits }}"
              memory: "{{ .Values.memory_limits }}"
          envFrom:
           - configMapRef:
              name: {{ .Chart.Name }}-config