{{- $lokins := (lookup "v1" "Namespace" "" "loki") }}
{{- if not $lokins }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/resource-policy": keep
  labels:
    name: {{ .Values.namespace }}
{{- end }}