{{- $monitoringns := (lookup "v1" "Namespace" "" "monitoring") }}
{{- if not $monitoringns }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels:
    name: {{ .Values.namespace }}
{{- end }}