druid.service=druid/broker
druid.plaintextPort=8082
druid.processing.buffer.sizeBytes=16MiB
druid.processing.numThreads=1
druid.processing.numMergeBuffers=1
druid.server.http.numThreads=10
druid.broker.http.numConnections=25
druid.broker.cache.useCache=false
druid.broker.cache.populateCache=false
