apiVersion: batch/v1
kind: Job
metadata:
  name: create-grafana-user
  namespace: {{ include "base.namespace" . }}
  annotations:
    deployment_version: "v2"
spec:
  template:
    metadata:
      labels:
        app: create-grafana-user
    spec:
      restartPolicy: Never
      containers:
      - name: create-grafana-user
        image: debian:bullseye-slim
        command:
        - sh
        - -c
        - |
          echo "Updating package repositories and installing required tools..."
          apt-get update && apt-get install -y curl jq postgresql-client

          echo "Waiting for Keycloak to be ready..."
          until curl --insecure -s -o /dev/null -w "%{http_code}" http://keycloak:80/auth/realms/grafana-auth/ > /dev/null; do
            sleep 5
          done

          echo "Keycloak is ready. Starting user creation..."

          # Obtain admin access token using admin credentials
          echo "Getting access token for admin user..."
          access_token=$(curl --insecure -s -X POST http://keycloak:80/auth/realms/master/protocol/openid-connect/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "client_id=admin-cli" \
            --data-urlencode "username={{ .Values.auth.adminUser }}" \
            --data-urlencode "password={{ .Values.auth.adminPassword }}" \
            --data-urlencode "grant_type=password" | jq -r '.access_token')

          if [ -z "$access_token" ]; then
            echo "Failed to get access token."
            exit 1
          fi

          echo "Access token retrieved successfully."

          # Create a new user in the grafana-oauth realm
          echo "Creating new Keycloak user..."
          create_user_response=$(curl --insecure -s -o response.json -w "%{http_code}" \
            -X POST http://keycloak:80/auth/admin/realms/grafana-oauth/users \
            -H "Authorization: Bearer $access_token" \
            -H "Content-Type: application/json" \
            -d '{
                  "username": "{{ .Values.grafanauser }}",
                  "enabled": true,
                  "credentials": [
                    {
                      "type": "password",
                      "value": "{{ .Values.grafanapassword}}",
                      "temporary": false
                    }
                  ]
                }')

          if [ "$create_user_response" -eq 201 ]; then
            echo "Keycloak user 'admin' created successfully in realm 'grafana-oauth."
          elif [ "$create_user_response" -eq 409 ]; then
            echo "User 'admin' already exists in realm 'grafana-oauth'."
          else
            echo "Failed to create user. HTTP status: $create_user_response"
            cat response.json
            exit 1
          fi

          