druid.service=druid/historical
druid.plaintextPort=8083
druid.processing.buffer.sizeBytes=16MiB
druid.processing.numThreads=1
druid.processing.numMergeBuffers=1
druid.server.http.numThreads=10
druid.segmentCache.locations=[{"path":"/druid/data/historical/store","maxSize":2147483648}]
druid.segmentCache.numLoadingThreads=2
druid.historical.cache.useCache=false
druid.historical.cache.populateCache=false
