{
 "title": "S3 Backup Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "bucket",
    "label": "bucket",
    "query": {
     "query": "label_values(s3_list_success{job=\"s3-backups\"},bucket)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(s3_list_success{job=\"s3-backups\", bucket=\"$bucket\"},prefix)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "title": "Total Number of Backup Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "s3_objects{job=\"s3-backups\", bucket=~\"$bucket\", prefix=~\"$app\"}",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Hours Since Last Backup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - s3_last_modified_object_date{job=\"s3-backups\", bucket=~\"$bucket\", prefix=~\"$app\"})",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Size of Last Backup File",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "s3_last_modified_object_size_bytes{job=\"s3-backups\", bucket=~\"$bucket\", prefix=~\"$app\"}",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Largest Backup File Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "s3_biggest_object_size_bytes{job=\"s3-backups\", bucket=~\"$bucket\", prefix=~\"$app\"}",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Backup Folder Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "s3_objects_size_sum_bytes{job=\"s3-backups\", bucket=~\"$bucket\", prefix=~\"$app\"}",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "PostgreSQL Backup Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=~\"postgresql\", container=~\"postgresql-backup\"} |= ``"
    }
   ]
  },
  {
   "title": "Redis Backup Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=~\"redis\", container=\"redis-backup\"} |= ``"
    }
   ]
  },
  {
   "title": "S3 Exporter Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{namespace=\"s3-exporter\"} |= ``"
    }
   ]
  }
 ]
}