{
 "title": "Volume Autoscaler",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Autoscaling Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "volume_autoscaler_settings_info",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Autoscaling Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "volume_autoscaler_release_info{job=\"additional-volume-autoscaler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaling Attempts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(volume_autoscaler_resize_attempted_total{job=\"additional-volume-autoscaler\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Scales",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(volume_autoscaler_resize_successful_total{job=\"additional-volume-autoscaler\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Scales",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(volume_autoscaler_resize_failure_total{job=\"additional-volume-autoscaler\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC's Above Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_autoscaler_num_pvcs_above_threshold{job=\"additional-volume-autoscaler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC's Below Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_autoscaler_num_pvcs_below_threshold{job=\"additional-volume-autoscaler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of PVCs in Autoscaling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_autoscaler_num_valid_pvcs{job=\"additional-volume-autoscaler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Autoscaling Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Autoscaling Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=\"volume-autoscaler\"} |= ``"
    }
   ]
  }
 ]
}