# This chart installs the custom grafana dashboards and datasources
namespace: ""
dashboards:
  label:
    grafana_dashboard: "1"
    system.monitoring: "true"
datasources:
  label:
    grafana_datasource: "1"
    system.monitoring: "true"

# You can additional data sourcres below
additionalDataSources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki-gateway.loki.svc.cluster.local
  jsonData:
    maxLines: 1000

# To add new dashboards, place the exported json in dashboards directory
# If any dashboards are added / modified / removed,
# bump up the chart version number in order to pick up changes