{{- $redisns := (lookup "v1" "Namespace" "" "redis") }}
{{- if not $redisns }}
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
{{ end }}