*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
master.sink.prometheusServlet.path=/metrics/prometheus/
worker.sink.prometheusServlet.path=/metrics/prometheus/
driver.sink.prometheusServlet.path=/metrics/prometheus/
applications.sink.prometheusServlet.path=/metrics/applications/prometheus/
executor.sink.prometheusServlet.path=/metrics/executors/prometheus/
