apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  SYSTEM_ENV: "{{ .Values.SYSTEM_ENV }}"
  TELEMETRY_KAFKA_COMPRESSION: "{{.Values.TELEMETRY_KAFKA_COMPRESSION}}"
  DRUID_HOST: "{{ .Values.druid_service.DRUID_HOST }}"
  DRUID_PORT: "{{ .Values.druid_service.DRUID_PORT }}"
  KAFKA_HOST: "{{ .Values.kafka_service.KAFKA_HOST }}"
  KAFKA_PORT: "{{ .Values.kafka_service.KAFKA_PORT }}"
  CLIENT_ID: "{{ .Values.kafka_service.CLIENT_ID }}"
  KAFKA_INITIAL_RETRY_TIME: "{{ .Values.kafka_service.KAFKA_INITIAL_RETRY_TIME }}"
  KAFKA_RETRIES: "{{ .Values.kafka_service.KAFKA_RETRIES }}"
  KAFKA_CONNECTION_TIMEOUT: "{{ .Values.kafka_service.KAFKA_CONNECTION_TIMEOUT }}"
  POSTGRES_HOST: "{{ .Values.postgres_service.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ .Values.postgres_service.POSTGRES_PORT }}"
  POSTGRES_DATABASE: "{{ .Values.postgres_service.POSTGRES_DATABASE }}"
  POSTGRES_USERNAME: "{{ .Values.postgres_service.POSTGRES_USERNAME }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres_service.POSTGRES_PASSWORD }}"
  REDIS_HOST: "{{ .Values.redis_service.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.redis_service.REDIS_PORT }}"
  EXHAUST_PROVIDER: "{{ .Values.exhaust_service.EXHAUST_PROVIDER }}"
  EXHAUST_REGION: "{{ .Values.exhaust_service.EXHAUST_REGION }}"
  LABEL_CONTAINER: "{{ .Values.exhaust_service.LABEL_CONTAINER }}"
  LABEL_CONTAINER_PREFIX: "{{ .Values.exhaust_service.LABEL_CONTAINER_PREFIX }}"
  STORAGE_URL_EXPIRY: "{{ .Values.exhaust_service.STORAGE_URL_EXPIRY }}"
