{{- if not (lookup "v1" "Secret" .Values.namespace .Values.global.docker_registry_secret_name) -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Values.global.docker_registry_secret_name }}
  namespace: {{ .Values.namespace }}
  annotations:
type: kubernetes.io/dockerconfigjson
{{ end }}
