{{- if and .Values.gateway.enabled (not (and .Values.enterprise.enabled .Values.enterprise.gelGateway)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.gatewayFullname" . }}
  namespace: {{ (include "base.namespace" $) | quote }}
  labels:
    {{- include "loki.gatewayLabels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- tpl .Values.gateway.nginxConfig.file . | indent 2 }}
{{- end }}
