namespace: "web-console"
replicaCount: 1
cpu_requests: 0.5
cpu_limits: 0.5
memory_requests: 512Mi
memory_limits: 1024Mi
image:
  repository: sanketikahub
  image_name: sb-obsrv-web-console
  tag: "1.0.0-GA"
  pullPolicy: "IfNotPresent"
ENV: dev
PORT: 3000
APP_NAME: obsrv-web-console
PROMETHEUS_URL: http://obsrv-monitoring-prometheus.monitoring:9090
HTTPS: false
REACT_APP_VERSION: "v1.2.0"
GENERATE_SOURCEMAP: false
REACT_APP_GRAFANA_URL: http://localhost:80
REACT_APP_SUPERSET_URL: http://localhost:8081
service:
  type: NodePort
  # Port exposed within the cluster
  port: 3000
  # Port on the pods
  targetPort: 3000
  # Port accessible externally on each node
  nodePort: 30501
