cloud_store_provider: "s3"
upload_manager: "com.pinterest.secor.uploader.S3UploadManager"
cloud_storage_bucket: ""
namespace: "secor"
storageClass: "gp2"
secor_env: "sb-dev"
image_repository: "sunbird/secor"
region: "us-east-2"
pullPolicy: "IfNotPresent"
jvm_memory: 1024m
image_tag: "0.29.16-java-11-gs"
timezone: "UTC"
secor_jobs:
  ingest-backup:
    replicas: 1
    consumer_group: "sb-dev_ingest"
    service_name: "ingest-backup"
    base_path: "telemetry-data/ingest"
    timestamp_key: "syncts"
    fallback_timestamp_key: ""
    topic: "sb-dev.ingest"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: "dataset"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000

  raw-backup:
    replicas: 1
    consumer_group: "sb-dev_raw"
    service_name: "raw"
    base_path: "telemetry-data/raw"
    timestamp_key: "obsrv_meta.syncts"
    fallback_timestamp_key: ""
    topic: "sb-dev.raw"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: "dataset"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000

  failed-backup:
    replicas: 1
    consumer_group: "sb-dev_failed"
    service_name: "failed"
    base_path: "telemetry-data/failed"
    timestamp_key: "obsrv_meta.syncts"
    fallback_timestamp_key: ""
    topic: "sb-dev.failed"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: "dataset"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000

  unique-backup:
    replicas: 1
    consumer_group: "sb-dev_unique"
    service_name: "unique"
    base_path: "telemetry-data/unique"
    timestamp_key: "obsrv_meta.syncts"
    fallback_timestamp_key: ""
    topic: "sb-dev.unique"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: "dataset"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000

  denorm-backup:
    replicas: 1
    consumer_group: "sb-dev_denorm"
    service_name: "denorm"
    base_path: "telemetry-data/denorm"
    timestamp_key: "obsrv_meta.syncts"
    fallback_timestamp_key: ""
    topic: "sb-dev.denorm"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: "dataset"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000

  transform-backup:
    replicas: 1
    consumer_group: "sb-dev_transform"
    service_name: "transform"
    base_path: "telemetry-data/transformed"
    timestamp_key: "obsrv_meta.syncts"
    fallback_timestamp_key: ""
    topic: "sb-dev.transform"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: "dataset"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000

  system-events:
    replicas: 1
    consumer_group: "sb-dev_system_events"
    service_name: "system-events"
    base_path: "telemetry-data/system-events"
    timestamp_key: "obsrv_meta.syncts"
    fallback_timestamp_key: ""
    topic: "sb-dev.system.events"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: "data.dataset"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000

  system-telemetry-events:
    replicas: 1
    consumer_group: "sb-dev_system_telemetry_events"
    service_name: "system-telemetry-events"
    base_path: "telemetry-data/system-telemetry-events"
    timestamp_key: "ets"
    fallback_timestamp_key: ""
    topic: "sb-dev.system.telemetry.events"
    kafka_broker_host: "kafka-headless.kafka.svc.cluster.local"
    zookeeper_quorum: "kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
    max_file_size: "100000000"
    max_file_age: "60"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: ""
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser" 
    storage:
      size: "1Gi"
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "128m"
      memory: "512Mi"
    lag_threshold_warning: 100000
    threads: "2"
    lag_threshold_critical: 200000 

alertrules:
  enabled: false

describedobject:
  name: "data-path"

serviceAccount:
  create: true
  name: secor-sa