{
 "title": "Promtail Metrics",
 "description": "promtail 2.4.x in k8s with kube-prometheus-stack metrics",
 "tags": [ "managed" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(promtail_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log messages - errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{namespace=\"$namespace\", container=\"promtail\", level=\"error\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Bytes dropped",
   "type": "graph",
   "description": "Number of bytes dropped because failed to be sent to the ingester after all retries.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_dropped_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Entries dropped",
   "type": "graph",
   "description": "Number of bytes dropped because failed to be sent to the ingester after all retries.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_dropped_entries_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "inflight requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inflight_requests{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (method,route)",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "Log messages - all",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Number of bytes encoded and ready to send",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_encoded_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Number of file bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_file_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Files active",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_files_active_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Number of read bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_read_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Number of read bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_read_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Number of sent bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_sent_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Number of sent entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_sent_entries_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Worst stream lag",
   "type": "graph",
   "description": "Difference between current time and last batch timestamp for successful sends",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(promtail_stream_lag_seconds{namespace=\"$namespace\", container=\"promtail\"}[1m])*60)",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Targets active",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_targets_active_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Number of failed targets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_targets_failed_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcp_connections{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (protocol)",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Per Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log messages - errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{namespace=\"$namespace\", container=\"promtail\", level=\"error\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes dropped",
   "type": "graph",
   "description": "Number of bytes dropped because failed to be sent to the ingester after all retries.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_dropped_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of bytes encoded and ready to send",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_encoded_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod  }}"
    }
   ]
  },
  {
   "title": "Entries dropped",
   "type": "graph",
   "description": "Number of bytes dropped because failed to be sent to the ingester after all retries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_dropped_entries_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of bytes total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_file_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod  }}"
    }
   ]
  },
  {
   "title": "Files active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_files_active_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_read_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of read lines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_read_lines_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_sent_bytes_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of sent entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_sent_entries_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Worst stream lag",
   "type": "graph",
   "description": "Difference between current time and last batch timestamp for successful sends",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(promtail_stream_lag_seconds{namespace=\"$namespace\", container=\"promtail\"}[1m])*60) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Targets active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_targets_active_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcp_connections{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod,protocol)",
     "legendFormat": "{{ pod }} {{ protocol }}"
    }
   ]
  },
  {
   "title": "Number of failed targets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_targets_failed_total{namespace=\"$namespace\", container=\"promtail\"}[$__rate_interval])) by (pod, reason)",
     "legendFormat": "{{ pod }} {{ reason }}"
    }
   ]
  }
 ]
}