{
 "title": "S3 Bucket Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "bucket",
    "label": "bucket",
    "query": {
     "query": "label_values(s3_list_success,bucket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "s3_objects_size_sum_bytes{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Count of Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "s3_objects{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Hours Since Last Modified Object",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(time() - s3_last_modified_object_date{bucket=~\"$bucket\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Size of Last Modified Object",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "s3_last_modified_object_size_bytes{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Largest Object Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "s3_biggest_object_size_bytes{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ListObjects API Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "s3_list_duration_seconds{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ListObjects API Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "s3_list_success{bucket=~\"$bucket\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 Exporter Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{namespace=\"s3-exporter\"} |= ``"
    }
   ]
  }
 ]
}