druid.service=druid/indexer
druid.plaintextPort=8091
druid.worker.capacity=2
druid.indexer.task.baseTaskDir=/druid/data/indexer/task
druid.indexer.task.restoreTasksOnRestart=true
druid.processing.buffer.sizeBytes=64MiB
druid.processing.numThreads=1
druid.processing.numMergeBuffers=1
druid.server.http.numThreads=25
druid.indexer.worker.globalIngestionHeapLimitBytes=536870912
