nameOverride: ""
fullnameOverride: "kafka-message-exporter"

replicaCount: 1

namespace: kafka
global:
  image:
    registry: "sanketikahub"

registry: ""
repository: "kafka-message-exporter"
tag: "v1.0.0-GA"
digest: ""

imagePullPolicy: IfNotPresent
imagePullSecrets: []

commonLabels:
  system.monitoring: "true"

commonAnnotations: {}

podAnnotations: {}

podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1001
  # fsGroup: 1001

securityContext: {}
  # readOnlyRootFilesystem: false
  # capabilities:
  #   drop:
  #   - ALL

# This block is an interface for k8s service spec.
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - paths:
      - /
      # host: chart-example.local

config:
  kafka:
    spark:
      host: "{{.Values.global.kafka.host}}:{{.Values.global.kafka.port}}"
      topic: "spark.stats"
      schema: "telemetry"
    obsrv:
      host: "{{.Values.global.kafka.host}}:{{.Values.global.kafka.port}}"
      topic: "sb-dev.stats"
      schema: "obsrv_meta"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

livenessProbe:
  httpGet:
    path: /health
    port: http
  # httpGet:
  #   path: "/healthz"
  #   port: 8080
  # initialDelaySeconds: 5
  # periodSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: http
  # httpGet:
  #   path: "/ready"
  #   port: 8080
  # initialDelaySeconds: 5
  # periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}

configmap:
  enabled: true
  mountPath: config

serviceAccount:
  create: true
  annotations: {}

serviceMonitor:
  enabled: true
  selectorLabels:
    release: monitoring
  endpoints:
  - port: http
    honorLabels: true
    relabelings:
    - action: labeldrop
      regex: ^pod$
  # - port: http # the name of the port in your service, assuming the primary service port is named 'http' in this example.
  #   path: /metrics
  #   interval: 30s
  #   scrapeTimeout: 10s
  #   honorLabels: true

# Example values.yaml structure
initContainers: {}
  # - name: init-myservice
  #   image: busybox:1.28
  #   command: ['sh', '-c', "until nslookup kubernetes.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

sidecars: {}
  # - name: log-reader # Sidecar container
  #   image: busybox # Use another busybox image
  #   command: ["/bin/sh"] # Override the default command
  #   args: ["-c", "tail -f /var/log/app.log"] # Run a shell script that tails the log file
