apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  name: {{ include "common.names.fullname" . }}-grafana-token-job-sa
  namespace: {{ include "base.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  name: {{ include "common.names.fullname" . }}-grafana-token-job-role
  namespace: {{ include "base.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  name: {{ include "common.names.fullname" . }}-grafana-token-job-rolebinding
  namespace: {{ include "base.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.names.fullname" . }}-grafana-token-job-role
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.fullname" . }}-grafana-token-job-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-create-grafana-secret
  namespace: {{ include "base.namespace" . }}
  labels:
    app: grafana
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      serviceAccountName: {{ include "common.names.fullname" . }}-grafana-token-job-sa
      containers:
        - name: {{ include "common.names.fullname" . }}-create-token
          image: sanketikahub/kubectl:1.32.0-r1
          command: ["/bin/sh"]
          args:
            - -c
            - |
              generate_token_and_create_secret() {
                  echo "generating token for 'grafana-{{ include "common.names.fullname" . }}-sa': $1"
                  response=$(curl -Ss "{{ .Values.global.grafana.grafana_url }}/api/serviceaccounts/$1/tokens" \
                  -H 'Accept: application/json' \
                  -H 'Content-type: application/json' \
                  -H "Authorization: Basic {{ printf "%s:%s" .Values.global.grafana.grafana_admin_user .Values.global.grafana.grafana_admin_password | b64enc }}" \
                  -d '{"name": "grafana-{{ include "common.names.fullname" . }}-sa"}')

                  echo "token response:"
                  echo $response
                  auth_token=$(echo "$response" | jq -r '.key')

                  if [ "$auth_token" = "null" ]; then
                      echo "unable to find the token for the service account. Please manually delete the service account and rerun this job."
                      exit 1
                  else
                      if ! kubectl get secret {{ include "common.names.fullname" . }}-grafana-secret -n {{ .Values.namespace }} > /dev/null 2>&1; then
                          echo "secret '{{ include "common.names.fullname" . }}-grafana-secret' does not exists..creating..."
                      else
                          echo "secret '{{ include "common.names.fullname" . }}-grafana-secret' already exists..deleting and recreating..."
                          kubectl delete secret {{ include "common.names.fullname" . }}-grafana-secret -n {{ .Values.namespace }}
                      fi
                      kubectl create secret generic {{ include "common.names.fullname" . }}-grafana-secret --from-literal=grafana_token="Bearer $auth_token" -n {{ .Values.namespace }}
                  fi
              }

              response=$(curl -Ssq "{{ .Values.global.grafana.grafana_url }}/api/serviceaccounts/search" \
                  -H 'Accept: application/json' \
                  -H 'Content-type: application/json' \
                  -H "Authorization: Basic {{ printf "%s:%s" .Values.global.grafana.grafana_admin_user .Values.global.grafana.grafana_admin_password | b64enc }}")
              id=$(echo "$response" | jq -r '.serviceAccounts[] | select(.name == "grafana-{{ include "common.names.fullname" . }}-sa") | .id')

              # Check if the service account already exists or not
              if [ -z "$id" ]; then
                  echo "The ID for the service account 'grafana-{{ include "common.names.fullname" . }}-sa' could not be found. Creating new service account."

                  response=$(curl -Ss -X POST "{{ .Values.global.grafana.grafana_url }}/api/serviceaccounts" \
                      -H 'Accept: application/json' \
                      -H 'Content-type: application/json' \
                      -H "Authorization: Basic {{ printf "%s:%s" .Values.global.grafana.grafana_admin_user .Values.global.grafana.grafana_admin_password | b64enc }}" \
                      -d '{"name": "grafana-{{ include "common.names.fullname" . }}-sa","role": "Admin","isDisabled": false}')

                  echo "SA creation response:"
                  echo $response
                  service_account_id=$(echo "$response" | jq -r '.id')

                  if [ -z "$service_account_id" ]; then
                      echo "failed to create service account"
                      exit 1;
                  else
                      generate_token_and_create_secret $service_account_id
                  fi
              else
                  echo "Service account already exists. The ID of the service account 'grafana-{{ include "common.names.fullname" . }}-sa' is: $id"

                  if ! kubectl get secret {{ include "common.names.fullname" . }}-grafana-secret -n {{ .Values.namespace }} > /dev/null 2>&1; then
                      echo "secret '{{ include "common.names.fullname" . }}-grafana-secret' does not exists..creating..."

                      curl -X DELETE "{{ .Values.global.grafana.grafana_url }}/api/serviceaccounts/$id" \
                          -H 'Accept: application/json' \
                          -H 'Content-type: application/json' \
                          -H "Authorization: Basic {{ printf "%s:%s" .Values.global.grafana.grafana_admin_user .Values.global.grafana.grafana_admin_password | b64enc }}"

                      response=$(curl -Ss -X POST "{{ .Values.global.grafana.grafana_url }}/api/serviceaccounts" \
                          -H 'Accept: application/json' \
                          -H 'Content-type: application/json' \
                          -H "Authorization: Basic {{ printf "%s:%s" .Values.global.grafana.grafana_admin_user .Values.global.grafana.grafana_admin_password | b64enc }}" \
                          -d '{"name": "grafana-{{ include "common.names.fullname" . }}-sa","role": "Admin","isDisabled": false}')

                      echo "SA creation response:"
                      echo $response
                      service_account_id=$(echo "$response" | jq -r '.id')

                      if [ -z "$service_account_id" ]; then
                          echo "failed to create service account"
                          exit 1;
                      else
                          generate_token_and_create_secret $service_account_id
                      fi
                  fi
                  exit 0
              fi
      restartPolicy: OnFailure

