apiVersion: batch/v1
kind: Job
metadata:
  name: submit-ingestion
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: druid
          image: "ubuntu:20.04"
          command:
          - sh
          - -c
          - |
            apt-get update &&
            apt-get install -y curl &&
            BASE_URL="http://{{ .Values.druid_router_host }}/{{ .Values.supervisor_path }}" &&
            {{ if .Values.druid_auth_enabled }}
            for spec in /etc/ingestion-spec/*.json; do
              curl -XPOST  -H 'Authorization: Basic {{ printf "%s" (printf "%s:%s" .Values.druid_admin_username .Values.druid_admin_password | b64enc) }}' -H 'Content-Type: application/json' -d @"$spec" "$BASE_URL"
            done
            {{- else}}
            for spec in /etc/ingestion-spec/*.json; do
              curl -XPOST -H 'Content-Type: application/json' -d @"$spec" "$BASE_URL"
            done
            {{end}}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/ingestion-spec
      volumes:
        - name: config-volume
          configMap:
            name: ingestion-spec-config
