#!/usr/bin/env bash
# Turns secrets/{private,public}.pem into secrets/tokens.env.
#
# In the helm install these are a Secret named openssl-secrets, created by
# helmcharts/bootstrapper; web-console mounts private.pem as
# USER_TOKEN_PRIVATE_KEY and dataset-api mounts public.pem as
# user_token_public_key (see each chart's templates/deployment.yaml).
#
# Compose has no equivalent of a Secret-as-env-var, and a PEM is multi-line, so
# the values are written double-quoted with \n escapes. Compose's env_file
# parser expands those back into real newlines inside the container.
#
# Regenerate the keypair with:
#   openssl genrsa -out secrets/private.pem 2048
#   openssl rsa -in secrets/private.pem -pubout -out secrets/public.pem
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
secrets="${here}/secrets"
out="${secrets}/tokens.env"

for f in private.pem public.pem; do
  [ -f "${secrets}/${f}" ] || { echo "missing ${secrets}/${f}" >&2; exit 1; }
done

escape_pem() {
  # Join lines with a literal backslash-n.
  awk 'BEGIN{ORS=""} {print $0 "\\n"}' "$1"
}

{
  echo "# Generated by scripts/gen-token-env.sh -- do not edit."
  echo "# Replaces the openssl-secrets Secret from the helm install."
  echo "USER_TOKEN_PRIVATE_KEY=\"$(escape_pem "${secrets}/private.pem")\""
  echo "user_token_public_key=\"$(escape_pem "${secrets}/public.pem")\""
} > "${out}"

chmod 600 "${out}"
echo "Wrote ${out}"
