apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  namespace: {{ .Values.namespace }}
  labels:
    app: command-api
data:
  service_config: |
{{ .Values.service_config | indent 4 }}
