---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    run: "{{ .Chart.Name }}-service"
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.http_port }}
  selector:
    run: {{ .Chart.Name }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        run: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
      - name: commandapi-config-volume
        configMap:
          name: "{{ .Chart.Name }}-config"
      imagePullSecrets:
        - name: {{ .Values.global.image.imagePullSecrets }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.global.azure.images.command_api.registry }}/{{ .Values.global.azure.images.command_api.image }}:{{ .Values.global.azure.images.command_api.digest }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.http_port }}
          name: http
        volumeMounts:
        - name: commandapi-config-volume
          mountPath: /app/src/config/service_config.yml
          subPath: service_config
        env:
        - name: system_env
          value: "{{ .Values.system_env }}"
