---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    run: "{{ .Release.Name }}-service"
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.http_port }}
  selector:
    run: {{ .Release.Name }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
      - name: commandapi-config-volume
        configMap:
          name: "{{ .Release.Name }}-config"
      # restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}
      {{ if .Values.global.azure.images.command_api }}
        image: "{{ .Values.global.azure.images.command_api.registry }}/{{ .Values.global.azure.images.command_api.image }}:{{ .Values.global.azure.images.command_api.digest }}"
      {{ else }}
        image: "{{ .Values.image }}"
      {{ end }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.http_port }}
          name: http
        volumeMounts:
        - name: commandapi-config-volume
          mountPath: /app/src/config/service_config.yml
          subPath: service_config