- name: "[PERSISTENT VOLUMES]: Failed to automatically expand storage volume."
  query: volume_autoscaler_resize_failure_total
  operator: gt
  threshold: [0]
  category: "Storage"
  frequency: 5m
  interval: 5m
  labels: 
    alert_code: "STORAGE_PV_003"
  description: "The system couldn’t increase storage space and may enter an unhealthy state if the issue continues."
  annotations: 
    summary: "The volume autoscaler failed to expand the storage space (PV) due to certain limitations of the cloud provider. As a result, the system may become unhealthy."
  severity: critical

- name: "[VELERO]:Kubernetes cluster backup not found."
  query: sum(increase(velero_backup_failure_total[$__range]))
  operator: gt
  threshold: [0]
  category: "Storage"
  frequency: 5m
  interval: 5m
  labels: 
    alert_code: "STORAGE_VELERO_008"
  description: "The backup for the cluster failed, which could impact the recovery process if there's a system issue."
  annotations: 
    summary: "The backup process for the Kubernetes cluster failed, resulting in the system and its associated data may not be recoverable in the event of a failure or outage, impacting availability, disaster recovery, and rollback capabilities."
  severity: critical

- name: "[VALKEY]: Detected higher memory usage than expected."
  query: sum(sum_over_time(redis_memory_used_bytes[$__range]) / sum_over_time(redis_memory_max_bytes[$__range])) * 100
  operator: gt
  threshold: [80]
  category: "Processing"
  frequency: 5m
  interval: 5m
  labels: 
    alert_code: "PROCESS_VALKEY_012"
  description: "All datasets are at risk of becoming unhealthy due to high memory usage"
  annotations: 
    summary: "High memory usage in Valkey can cause the data processing system to pause. As a result, no new data will be processed or available for querying."
  severity: critical

- name: "[UNIFIED PIPELINE]: Detected higher amount of processing lag than expected."
  query: sum(sum_over_time(kafka_consumergroup_lag{consumergroup="unified-pipeline-group"}[$__range]))
  operator: gt
  threshold: [5000000]
  category: "Processing"
  frequency: 5m
  interval: 1h
  labels: 
    alert_code: "PROCESS_UNIFIED_PIPELINE_013"
  description: "A large amount of data is still waiting to be processed. This may cause in querying the most recent data."
  annotations: 
    summary: "High pipeline lag in the dataset indicates processing of new data is delayed. Because of this delay, new data isn’t available when querying the dataset."
  severity: critical