druid.service=druid/coordinator
druid.plaintextPort=8081

# Merges the overlord into this process -- one JVM instead of two.
druid.coordinator.asOverlord.enabled=true
druid.coordinator.asOverlord.overlordService=druid/overlord

druid.coordinator.startDelay=PT10S
druid.coordinator.period=PT30S
druid.coordinator.balancer.strategy=diskNormalized
