alertmanager:
  alertmanagerSpec:
      resources:
          limits:
              cpu: 128m
              memory: 256Mi
          requests:
              cpu: 128m
              memory: 256Mi
prometheusOperator:
  resources:
    limits:
        cpu: 200m
        memory: 200Mi
    requests:
        cpu: 100m
        memory: 100Mi
    prometheusConfigReloader:
        resources:
            limits:
                cpu: 200m
                memory: 50Mi
            requests:
                cpu: 200m
                memory: 50Mi
kube-state-metrics:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
grafana:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
prometheus:
  server:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  prometheusSpec:
    retention: 90d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
prometheus-node-exporter:
  resources:
   limits:
      cpu: 100m
      memory: 64Mi
   requests:
    cpu: 100m
    memory: 32Mi