apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-console
    system.infra: "true"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-1"
  name: web-console
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-console
  template:
    metadata:
      labels:
        azure-extensions-usage-release-identifier: obsrv-base
        app: web-console
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.image.imagePullSecrets }}
      containers:
        - name: web-console
          image: "{{ .Values.global.azure.images.web_console.registry }}/{{ .Values.global.azure.images.web_console.image }}:{{ .Values.global.azure.images.web_console.digest }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "{{ .Values.cpu_requests }}"
              memory: "{{ .Values.memory_requests }}"
            limits:
              cpu: "{{ .Values.cpu_limits }}"
              memory: "{{ .Values.memory_limits }}"
          envFrom:
           - configMapRef:
              name: {{ .Chart.Name }}-config